services:
  faq-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=""
  faq-frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8001:80"
